spring:
  application:
    name: producer
    token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJpeXM5elYyZzZlemgxU3FidGJIUWhGVkZfMWdzRC1VZ1MweU5HR2RQVEk0In0.eyJleHAiOjE3Mzg4MzQzMzIsImlhdCI6MTczODgzNDAzMiwianRpIjoiM2UzYjI3NDAtZTdjZi00YWFlLThmNTgtZTI2MTUxZDc5NjE5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9UcnVuZ0hpZXUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMzJiYWNlNzEtODQwMC00M2E4LWE2M2MtZTk4ZWQ3ZGEyMzI1IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiamF2YS1kZW1vIiwic2Vzc2lvbl9zdGF0ZSI6Ijg3ZGI2NDVkLTZlNmYtNGU1MC1hNTNkLTk0YjIwYjlhM2Q3MiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy10cnVuZ2hpZXUiLCJvZmZsaW5lX2FjY2VzcyIsImFkbWluIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJqYXZhLWRlbW8iOnsicm9sZXMiOlsiY2xpZW50X2FkbWluIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiI4N2RiNjQ1ZC02ZTZmLTRlNTAtYTUzZC05NGIyMGI5YTNkNzIiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJUcnVuZyBIaWV1IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiaHR0aGlldSIsImdpdmVuX25hbWUiOiJUcnVuZyIsImZhbWlseV9uYW1lIjoiSGlldSJ9.ikVno9sL2ItDPsE5s1cskYw4xG0WFPh-plXwyXGngrZnBTB7qTCn6-aZRzr7zdyloT_sBoIuLvxPFe0LooeBqrJg4GJtXMFos1aySO5_VxqpZD0KYP5gxpAdh9YzfqIZHey0QqutkrYYH3DSxMiu0xygROUxG6fANLZ6AAnEXjRUtvzpRDjwUbrofckrKASFb_dQqtboA14fSA1gM900FVPKOosytWyUUjgoHajVnfAwHdTmxP5VIIcMBZmFXJzJRrNXGvHjmuV37OtL4DtlhOqjh2nIHgJA2KoxI_YwTy3X2cgI-Hdh-14Ko2MkdqWvL2G1QGi_GEGEGnNplfp8gw

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.springframework: DEBUG

server:
  port: 8087

